### ISSUE TITLE
ImportError in Cohere SDK 5.9.3: Broken import paths after patch

### ISSUE THREAD

**Issue by ofekby** [cohere-ai/cohere-python#584]
**SDK Version (required)**
Provide the version you are using. To get the version, run the following python snippet
```python
import cohere

print(cohere.__version__) # 5.9.3
```

**Describe the bug**
Seems like the version update of 5.9.3 have broken some import paths.

```
 from cohere.types.embed_response import EmbedResponse_EmbeddingsByType
ImportError: cannot import name 'EmbedResponse_EmbeddingsByType' from 'cohere.types.embed_response' (/root/.cache/pypoetry/virtualenvs/<some_path_part>/lib/python3.11/site-packages/cohere/types/embed_response.py)
```

I am using a fork of semantic-router, and it seems like the patch version of `5.9.3` broken the dependency. This is the import in context https://github.com/aurelio-labs/semantic-router/blob/413f147c2e731c77bb68974714e9874b4f471695/semantic_router/encoders/cohere.py#L5

Everything works well in `5.9.2` as far as I know.
